#!/bin/bash

# Install native dependencies
apt update
apt install -y curl make sudo build-essential

# Install dependencies
USER=root make depend

# Make release
if [ "$1" = 'frontend' ]; then
    make release-frontend release-frontend-github-pages
else
    make release-agent
fi
